{
 "title": "BYOP",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Registered Devices",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(byop_devices{registered=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Devices",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(byop_devices{registered=\"true\", up=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online Pixels",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(byop_pixels{registered=\"true\", up=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "dmx in",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(byop_dmx_in_update_duration_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "color update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(byop_device_color_update_duration_seconds_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "status update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*60", "type": "math" }
   ]
  },
  {
   "title": "Color update times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "byop_dmx_in_update_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "byop_dmx_in_update_duration_seconds{quantile=\"0.999\"}",
     "legendFormat": "99%"
    },
    { "expression": "1/15", "type": "math" },
    { "expression": "1/30", "type": "math" }
   ]
  },
  {
   "title": "Color update times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "byop_device_color_update_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "byop_device_color_update_duration_seconds{quantile=\"0.999\"}",
     "legendFormat": "99%"
    },
    { "expression": "1/15", "type": "math" },
    { "expression": "1/30", "type": "math" }
   ]
  },
  {
   "title": "Status update times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "byop_device_status_update_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "byop_device_status_update_duration_seconds{quantile=\"0.999\"}",
     "legendFormat": "99%"
    },
    { "expression": "1/15", "type": "math" },
    { "expression": "1/30", "type": "math" }
   ]
  }
 ]
}